#include "town.h"
#include "input.h"
#include "../entities/player.h"
#include <iostream>
#include <thread>
#include <chrono>

Town::Town(const std::string& name) : Location(name, location_Type::Friendly, 1) {}

void Town::enter(Player& player) {
    static auto lastRegen = std::chrono::steady_clock::now();
    
    clearScreen();
    std::cout << "You are in the safe town of " << this->getName() << ".\n";
    
    auto now = std::chrono::steady_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(now - lastRegen).count();
    
    if (elapsed >= 5) {
        int heal = Player::MAX_HP * 5 / 100;
        if (heal < 1) heal = 1;
        
        int oldHp = player.getHp();
        player.heal(heal);
        int actualHeal = player.getHp() - oldHp;
        
        if (actualHeal > 0) {
            std::cout << "You feel rested. HP regenerated by " << actualHeal << ".\n";
        }
        lastRegen = now;
    }
    
    std::this_thread::sleep_for(std::chrono::seconds(1));
}
